### ISSUE TITLE
Music Generation model using Memory Retention cells

### ISSUE THREAD

**Issue by Soubeer** [Niketkumardheeryan/ML-CaPsule#604] opened 2024-05-15 02:39 UTC
Hey there. I would like to add a new sub project/topic/example here which would be great for users who have interests in music creation and also for those who just want to try different instrumentals out.This can be done using Memory Retention methods,which will not only allow the model to remember what the user wanted before but also what the model itself provided as an output previously depending upon its importance.
I have been doing ML/DL tasks for quite a while now and have made projects and done an internship on the same domain.

I would like to take this issue under GSSOC'24 and solve it real quick.

Hope I make it to your sight.

Thanks..

**Comment by invigorzz313** [comment] 2024-05-15 04:57
This issue will be closed for being a duplicate of an earlier one.

**Closed** 2024-05-15 04:58 UTC
